### PR TITLE
[BISERVER-13338] - Data source domain object mutation while re-parsing

### PR DESCRIPTION
**Pull request by YuryBY**

### CODE REVIEW

**Comment by YuryBY** [comment]
@mchen-len-son, could you please take a look? - should be merged after https://github.com/pentaho/pentaho-metadata/pull/177

**Comment by YuryBY** [comment]
@mchen-len-son the PR was updated. Thanks.

**Comment by YuryBY** [comment]
@mchen-len-son, any updates?

**Comment by mchen-len-son** [comment]
This was already approved and merged once.
Now it's resent along with the updated changes for core metadata, which is just merged.
Merging this.

**Pull request merged**
