### PR TITLE
[BAD-170] Support for Spark

### PR DESCRIPTION
**Pull request by pavel-sakun**
Add spark plugin
https://github.com/pentaho/pentaho-kettle/pull/1230
@dkincade

### CODE REVIEW

**Comment by pavel-sakun** [comment]
@pentaho-nbaker

**Comment by kcruzada** [comment]
@pentaho-nbaker ... can you review this pull request.?

**Comment by kcruzada** [comment]
@pentaho-nbaker can you review the pull request?

**Comment by kcruzada** [comment]
@pentaho-nbaker @mbradbury2014 can you get pull request processed?

**Pull request merged**
